spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    username: javafood
    url: jdbc:oracle:thin:@todair.synology.me:51521:XE
    driverClassName: oracle.jdbc.driver.OracleDriver
    password: javafood
mybatis:
  mapper-locations: classpath:mybatis/mappers/**/**.xml
  config-location: classpath:mybatis/model/modelConfig.xml
server:
  servlet:
    jsp:
      init-parameters:
        development: 'true'


#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp
#
#spring.datasource.driverClassName=oracle.jdbc.driver.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@todair.synology.me:51521:XE
#spring.datasource.username=javafood
#spring.datasource.password=javafood
#
#mybatis.config-location=classpath:mybatis/model/modelConfig.xml
#mybatis.mapper-locations=classpath:mybatis/mappers/**/**.xml
#
#server.servlet.jsp.init-parameters.development=true